Task.create(title: 'Terminar MyPocket', done: false)
Task.create(title: 'Comprar Arroz', done: false)
Task.create(title: 'Terminar FMON 2020', done: false)
Task.create(title: 'Comprar teclado mecânico', done: false)
Task.create(title: 'Estudar Ruby On Rails', done: true)
Task.create(title: 'Estudar React', done: true)